import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const PRODUCTS_DATA = [
  {
    slug: "411-gravel",
    name: "#411 Gravel",
    category: "gravel",
    description:
      "Blended aggregate of #57 stone mixed with stone fines. The combination of larger crushed stone and fine particles creates a material that compacts firmly while maintaining good drainage — a versatile choice for driveways and base layers.",
    shortDescription:
      "Blend of 3/4\" stone and fine particles. Compacts firmly for driveways and base layers.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 55,
    sizeDescription: "Blend of 3/4\" stone and fine particles",
    colorDescription: "Typically gray",
    densityLow: 1.4,
    densityHigh: 1.55,
    bestFor: [
      "Driveway top layers",
      "Driveway resurfacing",
      "Compacted base layers",
    ],
    notFor: ["Decorative landscaping", "Barefoot walking areas"],
    commonUses: ["Driveways", "Driveway repairs", "Road base", "Parking areas"],
    pros: [
      "Compacts firmly into a stable surface",
      "Better drainage than crusher run",
      "Smooth driving surface",
      "Good for resurfacing existing driveways",
    ],
    cons: [
      "Dusty when dry",
      "Not decorative",
      "Can soften if drainage is poor",
    ],
    altNames: [],
    featured: false,
    sortOrder: 1,
  },
  {
    slug: "57-gravel",
    name: "#57 Gravel",
    category: "gravel",
    description:
      "Crushed stone approximately 3/4 to 1 inch in size. One of the most commonly used aggregates in construction and landscaping due to its versatility and excellent drainage characteristics.",
    shortDescription:
      "Washed 3/4\" to 1\" gravel. Popular for driveways, drainage, and landscaping.",
    price: 15.0,
    unit: "ton",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 35,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 45,
    sizeDescription: "3/4\" to 1\" angular crushed stone",
    colorDescription: "Gray, blue-gray, or brown depending on source rock",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Drainage systems",
      "Driveways (base layer)",
      "Concrete mix",
      "Pipe bedding",
    ],
    notFor: ["Walking surfaces", "Decorative landscaping"],
    commonUses: [
      "Driveways",
      "Drainage",
      "Concrete production",
      "Pipe bedding",
      "Backfill",
      "Parking areas",
    ],
    pros: [
      "Highly versatile for many applications",
      "Excellent drainage properties",
      "Compacts well when combined with fines",
      "Widely available at most suppliers",
      "Cost-effective for large projects",
    ],
    cons: [
      "Too coarse for comfortable walking",
      "Angular edges are sharp",
      "Shifts without edging or stabilization",
      "Requires a finer top layer for driveways",
      "Not decorative on its own",
    ],
    altNames: [],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "8-gravel",
    name: "#8 Gravel",
    category: "gravel",
    description:
      "Small crushed stone approximately 3/8 to 1/2 inch. Its smaller size makes it more comfortable underfoot than larger aggregates while still providing excellent drainage.",
    shortDescription:
      "Washed 3/8\" gravel perfect for walkways, patios, and driveway top dressing.",
    price: 15.0,
    unit: "ton",
    marketPriceLowPerTon: 22,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 28,
    marketPriceHighPerYard: 50,
    sizeDescription: "3/8\" to 1/2\" angular crushed stone",
    colorDescription: "Gray, blue-gray, tan, or brown",
    densityLow: 1.35,
    densityHigh: 1.5,
    bestFor: [
      "Walkways",
      "Patio surfaces",
      "Between pavers",
      "Driveway top dressing",
    ],
    notFor: ["Heavy-load driveways", "Steep grades"],
    commonUses: [
      "Walkways",
      "Patios",
      "Paver gaps",
      "Asphalt mixes",
      "Top dressing",
      "Drainage backfill",
    ],
    pros: [
      "Comfortable to walk on",
      "Compacts better than larger stone",
      "Fills gaps between pavers nicely",
      "Excellent drainage",
      "Smooth driveway finishing layer",
    ],
    cons: [
      "Can migrate without proper edging",
      "Not as stable as larger crushed stone",
      "May be tracked indoors by shoes",
      "Less commonly stocked than #57",
      "Dusty when dry",
    ],
    altNames: [],
    featured: false,
    sortOrder: 3,
  },
  {
    slug: "89-stone",
    name: "#89 Stone",
    category: "gravel",
    description:
      "Small angular crushed stone approximately 3/8 inch and smaller. The angular edges help it compact better than rounded alternatives like pea gravel, making it suitable for walkways and pipe bedding.",
    shortDescription:
      "Fine angular crushed stone for walkways, pipe bedding, and paver joints.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 22,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 28,
    marketPriceHighPerYard: 50,
    sizeDescription: "3/8\" or smaller angular crushed stone",
    colorDescription: "Gray, blue-gray, or tan",
    densityLow: 1.35,
    densityHigh: 1.5,
    bestFor: [
      "Walkway surfaces",
      "Between pavers",
      "Pipe bedding",
      "Asphalt mix",
    ],
    notFor: ["Driveways (base layer)", "Heavy-load areas"],
    commonUses: [
      "Walkways",
      "Pipe bedding",
      "Asphalt mix",
      "Between pavers",
      "Top dressing",
      "Drainage backfill",
    ],
    pros: [
      "Angular edges compact better than pea gravel",
      "Small size fills tight spaces",
      "Suitable for pipe bedding",
      "Comfortable walkway surface",
      "Excellent drainage",
    ],
    cons: [
      "Too small for driveway base",
      "Can migrate without edging",
      "Less decorative than pea gravel",
      "May be tracked indoors",
      "Not widely stocked everywhere",
    ],
    altNames: [],
    featured: false,
    sortOrder: 4,
  },
  {
    slug: "bank-run-gravel",
    name: "Bank Run Gravel",
    category: "gravel",
    description:
      "Naturally occurring mix of sand, gravel, and small stones excavated from pits or riverbanks. Minimal processing keeps the cost low, making it ideal for rural projects and general fill.",
    shortDescription:
      "Natural mix of sand, gravel, and soil. Ideal for fill and base material.",
    price: 2.0,
    unit: "ton",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 30,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 40,
    sizeDescription: "Unscreened blend from sand up to 2\" stones",
    colorDescription: "Varies by regional geology — typically tan to brown",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: ["Low-cost fill", "Rural and agricultural projects"],
    notFor: [
      "Finished surfaces",
      "Decorative landscaping",
      "Precise grading",
    ],
    commonUses: [
      "Rural driveways",
      "Base fill",
      "Backfill",
      "Construction fill",
    ],
    pros: [
      "Very low cost",
      "Minimal processing required",
      "Good general fill material",
    ],
    cons: [
      "Inconsistent particle size",
      "Poor compaction compared to crusher run",
      "Can contain excess sand or clay",
    ],
    altNames: ["Pit Run Gravel", "Natural Gravel"],
    featured: false,
    sortOrder: 5,
  },
  {
    slug: "crushed-limestone",
    name: "Crushed Limestone",
    category: "stone",
    description:
      "Crushed sedimentary rock with a pale gray to white appearance. Compacts firmly and brightens landscapes with its light color. Popular for driveways, pathways, and garden beds throughout the Midwest.",
    shortDescription:
      "Premium limestone aggregate for driveways, construction, and landscaping.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 45,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 50,
    sizeDescription:
      "Available from fine screenings to 3\", most common 3/4\" and 1.5\"",
    colorDescription: "Pale gray to off-white, slight yellow tint possible",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Driveways",
      "Pathways",
      "Parking pads",
      "Garden beds",
    ],
    notFor: ["Wet/muddy areas", "Acidic-soil gardens"],
    commonUses: [
      "Driveways",
      "Pathways",
      "Base material",
      "Garden beds",
      "Parking pads",
      "Erosion control",
    ],
    pros: [
      "Compacts firmly into a stable surface",
      "Light color brightens landscapes",
      "Good drainage properties",
      "Affordable in limestone regions",
      "Natural weed suppression",
    ],
    cons: [
      "Can get muddy when wet",
      "Limited color options",
      "May raise soil pH over time",
      "Dusty when dry",
      "Not available everywhere",
    ],
    altNames: [],
    featured: false,
    sortOrder: 6,
  },
  {
    slug: "crushed-stone",
    name: "Crushed Stone",
    category: "stone",
    description:
      "Angular, mechanically crushed rock available in various sizes. The interlocking angular shape provides excellent stability and load-bearing capacity, making it the backbone of construction and driveway projects.",
    shortDescription:
      "Angular crushed rock for driveways, road base, and foundations. Compacts firmly.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 55,
    sizeDescription:
      "Fine dust to 4\" (#8=3/8\", #57=3/4\"-1\", #3=1\"-2\", #1=2\"-4\")",
    colorDescription: "Gray, blue-gray, or tan depending on source rock",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Driveways",
      "Road base",
      "Foundations",
      "French drains",
    ],
    notFor: ["Barefoot walking", "Decorative landscaping"],
    commonUses: [
      "Driveways",
      "Road base",
      "Foundations",
      "Retaining wall backfill",
      "French drains",
      "Concrete aggregate",
    ],
    pros: [
      "Compacts firmly into a stable surface",
      "Excellent load-bearing capacity",
      "Interlocking shape prevents shifting",
      "Widely available and affordable",
      "Multiple sizes for different applications",
    ],
    cons: [
      "Angular edges uncomfortable underfoot",
      "Dusty when dry",
      "Less decorative appearance",
      "Sharp on bare feet",
      "May need periodic top-dressing",
    ],
    altNames: [],
    featured: true,
    sortOrder: 7,
  },
  {
    slug: "crusher-run",
    name: "Crusher Run",
    category: "gravel",
    description:
      "Dense blend of crushed stone and stone dust, from 1.5 inches down to fine particles. The fines lock the larger stones together for a self-compacting, stable surface — the go-to material for driveways and road bases.",
    shortDescription:
      "Crushed limestone aggregate perfect for driveways and base material. Compacts well.",
    price: 20.0,
    unit: "ton",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 35,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 45,
    sizeDescription: "1.5\" down to fine dust",
    colorDescription: "Gray or blue-gray",
    densityLow: 1.4,
    densityHigh: 1.6,
    bestFor: [
      "Driveways",
      "Parking pads",
      "Road base",
      "Foundation sub-base",
    ],
    notFor: ["Decorative landscaping", "Barefoot walking areas"],
    commonUses: [
      "Driveways",
      "Parking areas",
      "Road bases",
      "Foundation sub-bases",
      "Backfill",
      "Equipment pads",
    ],
    pros: [
      "Self-compacts into an extremely stable surface",
      "Single-layer application possible",
      "Excellent load-bearing capacity",
      "Affordable and widely available",
      "Fines lock stones together naturally",
    ],
    cons: [
      "Not decorative (utilitarian gray)",
      "Can get muddy with poor drainage",
      "Dusty when dry",
      "Tracks onto paved surfaces",
      "Requires compaction equipment for best results",
    ],
    altNames: ["Road Base", "Class 5", "ABC", "Aggregate Base Course"],
    featured: true,
    sortOrder: 8,
  },
  {
    slug: "decomposed-granite",
    name: "Decomposed Granite",
    category: "gravel",
    description:
      "Granite that has naturally weathered into small pieces and fine particles. Compacts into a firm, rustic walking surface that works beautifully in drought-tolerant and xeriscaping designs.",
    shortDescription:
      "Weathered granite for patios, pathways, and xeriscaping. Natural rustic look.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 45,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 50,
    sizeDescription: "1/4\" and smaller mix of fine particles and small chunks",
    colorDescription: "Gold, tan, brown, gray, or reddish-brown",
    densityLow: 1.35,
    densityHigh: 1.5,
    bestFor: [
      "Patios",
      "Pathways",
      "Xeriscaping",
      "Bocce courts",
    ],
    notFor: ["Heavy-traffic driveways", "Rainy climates", "Steep slopes"],
    commonUses: [
      "Patios",
      "Pathways",
      "Driveways",
      "Xeriscaping",
      "Ground cover",
      "Bocce courts",
    ],
    pros: [
      "Compacts into a firm walking surface",
      "Natural rustic appearance",
      "Permeable — allows water through",
      "Low cost compared to pavers",
      "Ideal for drought-tolerant landscaping",
    ],
    cons: [
      "Gets muddy in heavy rain",
      "Tracked indoors on shoes",
      "Decomposes further over time and needs replenishing",
      "Limited color options",
      "Not suitable for heavy vehicle traffic",
    ],
    altNames: [],
    featured: true,
    sortOrder: 9,
  },
  {
    slug: "pea-gravel",
    name: "Pea Gravel",
    category: "gravel",
    description:
      "Small, naturally rounded stones about 3/8 inch in diameter. Smooth texture and attractive natural colors make it one of the most popular choices for patios, walkways, and decorative landscaping.",
    shortDescription:
      "Small rounded stones ideal for patios, walkways, and decorative landscaping.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 50,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 60,
    sizeDescription: "1/4\" to 3/8\" rounded stones",
    colorDescription:
      "Tan, brown, white, gray, and rust — mixed blends available",
    densityLow: 1.3,
    densityHigh: 1.45,
    bestFor: [
      "Patios",
      "Walkways",
      "Landscaping beds",
      "Garden paths",
      "Playgrounds",
    ],
    notFor: ["Driveways", "Steep slopes", "High-traffic areas"],
    commonUses: [
      "Patios",
      "Walkways",
      "Playgrounds",
      "Drainage",
      "Landscaping beds",
      "Garden paths",
    ],
    pros: [
      "Affordable and widely available",
      "Smooth and comfortable underfoot",
      "Excellent drainage properties",
      "Attractive natural colors",
      "Easy to install",
    ],
    cons: [
      "Shifts and migrates easily",
      "Poor compaction for driveways",
      "Requires edging to contain",
      "Tracked indoors on shoes",
      "Difficult to shovel snow from",
    ],
    altNames: [],
    featured: true,
    sortOrder: 10,
  },
  {
    slug: "river-rock",
    name: "River Rock",
    category: "stone",
    description:
      "Naturally rounded stones smoothed by centuries of water erosion, available from 1 to 5+ inches. Their beautiful, organic shapes make them a top choice for dry creek beds, water features, and decorative borders.",
    shortDescription:
      "Naturally rounded decorative stones for landscaping, drainage, and water features.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 40,
    marketPriceHighPerTon: 100,
    marketPriceLowPerYard: 45,
    marketPriceHighPerYard: 120,
    sizeDescription: "1\"-2\" (small) to 5\"+ (boulders)",
    colorDescription: "Gray, brown, tan, white, black, and multi-colored",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: [
      "Dry creek beds",
      "Decorative borders",
      "Erosion control",
      "Water features",
    ],
    notFor: [
      "Walking surfaces",
      "Driveways",
      "Areas needing compaction",
    ],
    commonUses: [
      "Landscaping",
      "Drainage",
      "Dry creek beds",
      "Decorative borders",
      "Erosion control",
      "Pond and water features",
    ],
    pros: [
      "Beautiful natural appearance",
      "Extremely durable and long-lasting",
      "Resists displacement by water",
      "No sharp edges",
      "Very low maintenance",
    ],
    cons: [
      "More expensive than crushed stone",
      "Heavy and difficult to move",
      "Unsuitable as a walking surface",
      "Cannot be compacted for stability",
      "Limited structural use",
    ],
    altNames: [],
    featured: true,
    sortOrder: 11,
  },
  {
    slug: "fill-dirt",
    name: "Fill Dirt",
    category: "soil",
    description:
      "Subsoil material free of organic matter. Its stability and resistance to decomposition make it ideal for grading, filling depressions, and building up elevation before adding topsoil or gravel.",
    shortDescription:
      "Clean fill dirt perfect for grading, backfill, and landscaping projects.",
    price: 2.0,
    unit: "ton",
    marketPriceLowPerTon: 5,
    marketPriceHighPerTon: 15,
    marketPriceLowPerYard: 8,
    marketPriceHighPerYard: 25,
    sizeDescription: "Fine to coarse soil particles, no organic matter",
    colorDescription: "Tan to reddish-brown",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: [
      "Grading and leveling",
      "Filling holes and depressions",
      "Raising elevation",
      "Retaining wall backfill",
    ],
    notFor: ["Planting", "Surface applications", "Drainage"],
    commonUses: [
      "Grading",
      "Filling depressions",
      "Raising elevation",
      "Backfill",
      "Construction prep",
      "Under slabs",
    ],
    pros: [
      "Very affordable",
      "Compacts firmly",
      "Does not decompose or settle like topsoil",
      "Widely available",
      "Ideal base under gravel or concrete",
    ],
    cons: [
      "Not suitable for growing plants",
      "Must be debris-free for structural use",
      "May contain clay which drains poorly",
      "Needs layered compaction for best results",
      "Quality varies by source",
    ],
    altNames: [],
    featured: false,
    sortOrder: 12,
  },
  {
    slug: "topsoil",
    name: "Topsoil",
    category: "soil",
    description:
      "Nutrient-rich upper layer of soil essential for growing plants, establishing lawns, and building garden beds. Screened topsoil provides a uniform, ready-to-use growing medium.",
    shortDescription:
      "Natural unprocessed topsoil for landscaping and gardening.",
    price: 8.0,
    unit: "ton",
    marketPriceLowPerTon: 12,
    marketPriceHighPerTon: 30,
    marketPriceLowPerYard: 15,
    marketPriceHighPerYard: 40,
    sizeDescription: "Fine crumbly texture (screened through 3/8\" or 1/2\" screen)",
    colorDescription: "Dark brown to black",
    densityLow: 1.1,
    densityHigh: 1.4,
    bestFor: [
      "Lawn establishment",
      "Garden beds",
      "Raised beds",
      "Grading for sod",
    ],
    notFor: ["Structural fill", "Under pavers or gravel", "Drainage"],
    commonUses: [
      "Lawn seeding",
      "Garden beds",
      "Raised beds",
      "Landscape grading",
      "Sod installation",
      "Tree and shrub planting",
    ],
    pros: [
      "Rich in nutrients for plant growth",
      "Ideal growing medium",
      "Dark color absorbs warmth for plants",
      "Screened options ready to use immediately",
      "Essential for any planting project",
    ],
    cons: [
      "Settles significantly over time",
      "Quality varies widely by source",
      "Can contain weed seeds",
      "Heavy when wet",
      "Never use as structural fill",
    ],
    altNames: [],
    featured: false,
    sortOrder: 13,
  },
  {
    slug: "fill-sand",
    name: "Fill Sand",
    category: "sand",
    description:
      "Quality fill sand suitable for construction and backfill applications. Provides a stable, level base for pavers, retaining walls, and other construction projects.",
    shortDescription:
      "Quality fill sand for construction and backfill applications.",
    price: 4.0,
    unit: "ton",
    marketPriceLowPerTon: 10,
    marketPriceHighPerTon: 25,
    marketPriceLowPerYard: 15,
    marketPriceHighPerYard: 35,
    sizeDescription: "Fine granular sand",
    colorDescription: "Tan to light brown",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: [
      "Construction base layers",
      "Backfill applications",
      "Leveling surfaces",
    ],
    notFor: ["Decorative use", "Concrete mix (use washed sand)", "Planting"],
    commonUses: [
      "Construction fill",
      "Backfill",
      "Leveling",
      "Pipe bedding",
      "Under pavers",
    ],
    pros: [
      "Affordable and widely available",
      "Easy to level and grade",
      "Good compaction properties",
      "Versatile construction material",
    ],
    cons: [
      "Not suitable for decorative applications",
      "Can wash out without containment",
      "May contain fine clay particles",
    ],
    altNames: [],
    featured: false,
    sortOrder: 14,
  },
  {
    slug: "washed-sand",
    name: "Washed Sand",
    category: "sand",
    description:
      "Clean sand mechanically washed to remove fines, dust, and clay particles. Used in concrete production, masonry, and any application requiring clean, uniform sand.",
    shortDescription:
      "Clean washed sand for construction, masonry, and landscaping.",
    price: null,
    unit: "call",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 35,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 45,
    sizeDescription: "Fine to medium uniform granules",
    colorDescription: "Light tan to off-white",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: [
      "Concrete mix",
      "Masonry and mortar",
      "Sandboxes",
    ],
    notFor: ["Structural fill", "Base layers"],
    commonUses: [
      "Concrete production",
      "Masonry",
      "Sandboxes",
      "Landscaping",
      "Golf course bunkers",
    ],
    pros: [
      "Clean and free of contaminants",
      "Uniform particle size",
      "Excellent for concrete and mortar",
    ],
    cons: [
      "More expensive than fill sand",
      "Washes away easily on slopes",
      "Call for current pricing",
    ],
    altNames: [],
    featured: false,
    sortOrder: 15,
  },
  {
    slug: "stone-dust",
    name: "Stone Dust",
    category: "stone",
    description:
      "Finely crushed aggregate with particles smaller than 1/4 inch. Compacts very tightly to create a smooth, level surface — the standard base material for paver installations and walkways.",
    shortDescription:
      "Fine crushed stone dust ideal for paver base and leveling.",
    price: null,
    unit: "call",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 30,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 40,
    sizeDescription: "Under 1/4\" fine particles",
    colorDescription: "Gray or tan",
    densityLow: 1.4,
    densityHigh: 1.6,
    bestFor: [
      "Paver installations",
      "Leveling uneven ground",
      "Compacted walking surfaces",
    ],
    notFor: ["Driveways", "High-drainage applications"],
    commonUses: [
      "Paver base",
      "Walkways",
      "Patios",
      "Leveling layers",
      "Pathways",
    ],
    pros: [
      "Compacts very tightly",
      "Creates a smooth level surface",
      "Affordable and widely available",
      "Easy to shape and grade",
    ],
    cons: [
      "Poor drainage",
      "Gets muddy if overwatered",
      "Dusty when dry",
      "Erodes without proper edging",
    ],
    altNames: ["Crusher Fines", "Screenings", "Rock Dust"],
    featured: false,
    sortOrder: 16,
  },
  {
    slug: "rip-rap",
    name: "Rip Rap",
    category: "stone",
    description:
      "Large, heavy angular stones ranging from 6 to 24+ inches, weighing 25 to 500+ pounds per stone. Engineered for erosion control along shorelines, stream banks, and steep slopes.",
    shortDescription:
      "Large angular stones for erosion control, shoreline protection, and slope stabilization.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 35,
    marketPriceHighPerTon: 80,
    marketPriceLowPerYard: 45,
    marketPriceHighPerYard: 100,
    sizeDescription: "6-24\" (up to 36\"), 25-500+ lbs per stone",
    colorDescription: "Gray, blue-gray, tan, or brown",
    densityLow: 1.4,
    densityHigh: 1.6,
    bestFor: [
      "Shoreline protection",
      "Stream bank stabilization",
      "Steep slope erosion control",
      "Culvert outlets",
    ],
    notFor: [
      "Driveways",
      "Walkways",
      "Decorative landscaping",
      "Small residential projects",
    ],
    commonUses: [
      "Shoreline protection",
      "Stream bank stabilization",
      "Bridge abutments",
      "Slope stabilization",
      "Culvert outlets",
      "Retaining wall faces",
    ],
    pros: [
      "Extremely effective at preventing erosion",
      "Heavy weight resists water displacement",
      "Decades of durability",
      "Angular shape interlocks for stability",
      "Natural appearance along waterways",
    ],
    cons: [
      "Very heavy — requires heavy equipment",
      "Expensive for large-scale projects",
      "Not suitable for foot traffic",
      "Needs engineering for major installations",
      "Limited decorative appeal",
    ],
    altNames: ["Armor Stone", "Rip Rap Stone", "Shot Rock"],
    featured: false,
    sortOrder: 17,
  },
  {
    slug: "recycled-asphalt",
    name: "Recycled Asphalt",
    category: "gravel",
    description:
      "Reclaimed asphalt pavement that has been crushed and screened. Compacts into a hard, semi-sealed surface that reduces dust and provides excellent traction at a fraction of the cost of new asphalt.",
    shortDescription:
      "Reclaimed crushed asphalt for low-cost driveways and parking areas.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 30,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 45,
    sizeDescription: "Under 1\" pieces of crushed reclaimed asphalt",
    colorDescription: "Black or dark gray",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Low-cost driveways",
      "High-traffic areas",
      "Dust control",
    ],
    notFor: ["Decorative landscaping", "Garden areas"],
    commonUses: [
      "Driveways",
      "Parking areas",
      "Rural roads",
      "Access roads",
    ],
    pros: [
      "Very affordable",
      "Compacts into a hard surface",
      "Less dust than traditional gravel",
      "Reuses existing materials — eco-friendly",
    ],
    cons: [
      "Can soften in extreme heat",
      "Dark color absorbs and retains heat",
      "Limited availability in some regions",
    ],
    altNames: ["RAP", "Millings"],
    featured: false,
    sortOrder: 18,
  },
  {
    slug: "washed-gravel",
    name: "Washed Gravel",
    category: "gravel",
    description:
      "Crushed or rounded stone mechanically washed to remove all fines and dust. The clean, uniform material provides superior drainage for French drains, foundation backfill, and septic systems.",
    shortDescription:
      "Clean washed gravel for drainage, French drains, and foundation backfill.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 45,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 60,
    sizeDescription: "3/4\" (#57), 1\"-2\", or mixed clean sizes",
    colorDescription: "Gray, tan, or off-white",
    densityLow: 1.3,
    densityHigh: 1.5,
    bestFor: [
      "Drainage systems",
      "Moisture control",
      "French drains",
      "Foundation backfill",
      "Septic systems",
    ],
    notFor: ["Driveways", "Walkways", "Load-bearing surfaces"],
    commonUses: [
      "French drains",
      "Foundation backfill",
      "Septic systems",
      "Pipe bedding",
      "Drainage trenches",
    ],
    pros: [
      "Excellent drainage — no fines to clog",
      "No dust or mud",
      "Does not retain water",
      "Clean uniform appearance",
    ],
    cons: [
      "Does not compact into a firm surface",
      "Can shift under load",
      "Requires edging or containment",
    ],
    altNames: [],
    featured: false,
    sortOrder: 19,
  },
  {
    slug: "construction-gravel",
    name: "Construction Gravel",
    category: "gravel",
    description:
      "Broad category of mixed-size stone for general building and site work. A workhorse material for construction sites, temporary roads, and base preparation.",
    shortDescription:
      "Mixed-size construction aggregate for base layers, backfill, and site work.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 35,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 50,
    sizeDescription: "Mixed crushed stone, fines to 1\"+",
    colorDescription: "Varies by quarry — typically gray",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "General construction",
      "Base preparation",
      "Utility work",
    ],
    notFor: ["Decorative landscaping", "Finished surfaces"],
    commonUses: [
      "Construction sites",
      "Base layers",
      "Backfill",
      "Temporary roads",
    ],
    pros: [
      "Versatile for many construction needs",
      "Readily available",
      "Cost-effective",
      "Works for many applications",
    ],
    cons: [
      "Inconsistent sizing",
      "Not suitable for aesthetics",
      "Composition varies by supplier",
    ],
    altNames: [],
    featured: false,
    sortOrder: 20,
  },
  {
    slug: "compost",
    name: "Compost",
    category: "soil",
    description:
      "Decomposed organic matter that enriches soil structure and fertility. Improves water retention in sandy soils, drainage in clay soils, and adds beneficial microorganisms for healthier plants.",
    shortDescription:
      "Nutrient-rich organic compost for soil amendment, garden beds, and lawn care.",
    price: null,
    unit: "ton",
    marketPriceLowPerTon: 15,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 20,
    marketPriceHighPerYard: 50,
    sizeDescription: "Fine, crumbly texture",
    colorDescription: "Dark brown to black",
    densityLow: 0.8,
    densityHigh: 1.2,
    bestFor: [
      "Soil amendment",
      "Garden beds",
      "Lawn top-dressing",
      "Raised bed mix",
    ],
    notFor: [
      "Structural fill",
      "Drainage",
      "Direct planting (too rich)",
    ],
    commonUses: [
      "Soil amendment",
      "Garden beds",
      "Lawn top-dressing",
      "Raised beds",
      "Tree and shrub planting",
      "Seed starting mixes",
    ],
    pros: [
      "Improves soil structure and fertility",
      "Increases water retention in sandy soils",
      "Improves drainage in clay soils",
      "Adds beneficial microorganisms",
      "Reduces need for chemical fertilizers",
    ],
    cons: [
      "Quality varies by source",
      "Can be odorous when fresh",
      "May contain weed seeds",
      "Too rich for direct planting alone",
      "Settles significantly over time",
    ],
    altNames: [],
    featured: false,
    sortOrder: 21,
  },
  {
    slug: "landscape-rock",
    name: "Landscape Rock",
    category: "stone",
    description:
      "Decorative natural stone for gardens, borders, and outdoor features. Available in various sizes and colors to complement any landscape design.",
    shortDescription:
      "Decorative landscape rock for gardens and outdoor features.",
    price: null,
    unit: "call",
    marketPriceLowPerTon: 40,
    marketPriceHighPerTon: 120,
    marketPriceLowPerYard: 50,
    marketPriceHighPerYard: 150,
    sizeDescription: "Various sizes from 2\" to 12\"+",
    colorDescription: "Varies — natural earth tones",
    densityLow: 1.3,
    densityHigh: 1.6,
    bestFor: [
      "Garden borders",
      "Decorative ground cover",
      "Water features",
      "Accent areas",
    ],
    notFor: ["Driveways", "Base layers", "Walking surfaces"],
    commonUses: [
      "Garden beds",
      "Borders",
      "Water features",
      "Decorative ground cover",
      "Accent landscaping",
    ],
    pros: [
      "Beautiful natural appearance",
      "Low maintenance",
      "Long-lasting",
      "Many color and size options",
    ],
    cons: [
      "Higher cost than utility aggregates",
      "Heavy to move",
      "Call for current pricing and availability",
    ],
    altNames: [],
    featured: false,
    sortOrder: 22,
  },
  {
    slug: "4-gravel",
    name: "#4 Gravel",
    category: "gravel",
    description:
      "Medium-large crushed stone ranging from 1.5 to 2.5 inches. Its size provides excellent drainage and stability for base applications, French drains, and erosion control.",
    shortDescription:
      "1.5\" to 2.5\" gravel for drainage and base applications.",
    price: null,
    unit: "call",
    marketPriceLowPerTon: 20,
    marketPriceHighPerTon: 40,
    marketPriceLowPerYard: 25,
    marketPriceHighPerYard: 55,
    sizeDescription: "1.5\" to 2.5\" angular crushed stone",
    colorDescription: "Gray, blue-gray depending on source",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Drainage applications",
      "Base layers for heavy loads",
      "French drains",
    ],
    notFor: ["Walking surfaces", "Driveway top layer", "Decorative use"],
    commonUses: [
      "Drainage",
      "Base applications",
      "French drains",
      "Erosion control",
      "Backfill",
    ],
    pros: [
      "Excellent drainage due to large voids",
      "Good stability for base layers",
      "Cost-effective for drainage projects",
    ],
    cons: [
      "Too large for walking surfaces",
      "Requires smaller stone top layer",
      "Call for current pricing",
    ],
    altNames: [],
    featured: false,
    sortOrder: 23,
  },
  {
    slug: "9-gravel",
    name: "#9 Gravel",
    category: "gravel",
    description:
      "Fine washed gravel ideal for pipe bedding and drainage applications. The small, uniform size fills tight spaces and provides consistent support around pipes and utilities.",
    shortDescription:
      "Fine washed gravel ideal for pipe bedding and drainage applications.",
    price: 8.0,
    unit: "ton",
    marketPriceLowPerTon: 18,
    marketPriceHighPerTon: 35,
    marketPriceLowPerYard: 22,
    marketPriceHighPerYard: 45,
    sizeDescription: "Under 3/8\" fine angular stone",
    colorDescription: "Gray to light tan",
    densityLow: 1.35,
    densityHigh: 1.5,
    bestFor: [
      "Pipe bedding",
      "Drainage backfill",
      "Utility trenches",
    ],
    notFor: ["Driveways", "Walking paths", "Decorative landscaping"],
    commonUses: [
      "Pipe bedding",
      "Drainage",
      "Utility trenches",
      "Backfill around foundations",
    ],
    pros: [
      "Perfect size for pipe bedding",
      "Uniform and consistent",
      "Good drainage",
      "Fills tight spaces",
    ],
    cons: [
      "Too fine for driveways",
      "Not decorative",
      "Can migrate without containment",
    ],
    altNames: [],
    featured: false,
    sortOrder: 24,
  },
  {
    slug: "8-fractured-gravel",
    name: "#8 Fractured Gravel (Washed)",
    category: "gravel",
    description:
      "Washed fractured gravel with angular edges in the 3/8\" to 1/2\" size range. The angular fracture provides better interlocking than rounded pea gravel while the washing removes dust and fines.",
    shortDescription:
      "Washed fractured gravel, 3/8\" to 1/2\" size. Great for driveways and walkways.",
    price: 28.0,
    unit: "ton",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 45,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 55,
    sizeDescription: "3/8\" to 1/2\" angular, fractured and washed",
    colorDescription: "Gray to blue-gray",
    densityLow: 1.35,
    densityHigh: 1.5,
    bestFor: [
      "Driveway top dressing",
      "Walkways",
      "Decorative gravel beds",
    ],
    notFor: ["Base layers (too small)", "Drainage (use larger stone)"],
    commonUses: [
      "Driveways",
      "Walkways",
      "Patio surfaces",
      "Decorative beds",
    ],
    pros: [
      "Angular edges interlock better than rounded stone",
      "Washed — clean and dust-free",
      "Attractive finished appearance",
      "Good for top layer applications",
    ],
    cons: [
      "Higher cost than unwashed alternatives",
      "Can still shift without edging",
      "Angular edges on bare feet",
    ],
    altNames: [],
    featured: false,
    sortOrder: 25,
  },
  {
    slug: "oversized-gravel",
    name: "Oversized Gravel (Washed)",
    category: "gravel",
    description:
      "Large washed gravel for drainage, erosion control, and decorative applications. The larger size provides excellent water flow and visual impact in landscape designs.",
    shortDescription:
      "Large washed gravel for drainage, erosion control, and decorative use.",
    price: 28.0,
    unit: "ton",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 50,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 65,
    sizeDescription: "2\" to 4\" washed stone",
    colorDescription: "Gray, tan, or mixed earth tones",
    densityLow: 1.3,
    densityHigh: 1.55,
    bestFor: [
      "Drainage ditches",
      "Erosion control",
      "Decorative landscape features",
    ],
    notFor: ["Driveways", "Walking surfaces", "Compacted base layers"],
    commonUses: [
      "Drainage",
      "Erosion control",
      "Decorative features",
      "Dry creek beds",
      "Retaining wall backfill",
    ],
    pros: [
      "Excellent drainage with large voids",
      "Washed clean — no dust or mud",
      "Decorative impact in landscaping",
      "Resists displacement by water",
    ],
    cons: [
      "Not walkable",
      "Cannot be compacted",
      "Higher cost than standard gravel",
    ],
    altNames: [],
    featured: false,
    sortOrder: 26,
  },
  {
    slug: "57-limestone",
    name: "#57 Limestone",
    category: "stone",
    description:
      "Premium crushed limestone in the standard #57 size (3/4\" to 1\"). Combines the versatility of #57 gravel with the bright, clean appearance and natural alkalinity of limestone.",
    shortDescription:
      "Premium limestone aggregate for driveways, construction, and landscaping.",
    price: 38.0,
    unit: "load",
    marketPriceLowPerTon: 25,
    marketPriceHighPerTon: 50,
    marketPriceLowPerYard: 30,
    marketPriceHighPerYard: 60,
    sizeDescription: "3/4\" to 1\" crushed limestone",
    colorDescription: "Pale gray to off-white",
    densityLow: 1.35,
    densityHigh: 1.55,
    bestFor: [
      "Driveways requiring a clean look",
      "Landscaping borders",
      "Drainage systems",
    ],
    notFor: ["Acidic-soil gardens", "Areas where pH sensitivity matters"],
    commonUses: [
      "Driveways",
      "Landscaping",
      "Drainage",
      "Construction base",
      "Decorative ground cover",
    ],
    pros: [
      "Bright, clean appearance",
      "Compacts well with fines",
      "Good drainage",
      "Premium aesthetic for landscaping",
    ],
    cons: [
      "Higher cost than standard #57 gravel",
      "Raises soil pH over time",
      "Limited regional availability",
    ],
    altNames: [],
    featured: false,
    sortOrder: 27,
  },
];

const COST_GUIDES_DATA = [
  {
    slug: "delivery-cost",
    title: "Gravel Delivery Cost",
    subtitle: "What to expect for delivery pricing",
    description:
      "Delivery adds $50-$200 to most gravel orders depending on distance and quantity. Understanding delivery costs helps you budget accurately for your project.",
    icon: "truck",
    sortOrder: 1,
    content: {
      priceRange: "$50-$200 added to order",
      perTonRange: "$20-$100 per ton delivered",
      perYardRange: "$25-$120 per yard delivered",
      sections: [
        {
          title: "Material Cost Ranges",
          items: [
            { material: "Crushed Stone", range: "$20-$40/ton" },
            { material: "#57 Gravel", range: "$20-$35/ton" },
            { material: "Pea Gravel", range: "$25-$50/ton" },
            { material: "River Rock", range: "$40-$100/ton" },
            { material: "Crusher Run", range: "$20-$35/ton" },
          ],
        },
        {
          title: "Truck Capacities",
          items: [
            { type: "Standard Tandem", capacity: "12-15 tons (8-10 yd³)" },
            { type: "Tri-Axle", capacity: "18-22 tons" },
            { type: "Super Dump", capacity: "24-26 tons" },
          ],
        },
        {
          title: "Delivery Distance Pricing",
          items: [
            { distance: "Local (10-20 mile radius)", cost: "$50-$100 flat rate" },
            { distance: "Extended radius", cost: "$100-$200+" },
            { distance: "Per-mile surcharge", cost: "$5-$10 per mile beyond base zone" },
          ],
        },
      ],
      tips: [
        "Free delivery is often available on orders of 5-10+ tons",
        "Ensure a minimum 10-foot-wide path for truck access",
        "Overhead clearance of 14 feet is required for dump trucks",
        "Muskingum Materials delivers up to 20 tons per load throughout Southeast Ohio",
      ],
    },
  },
  {
    slug: "driveway-cost",
    title: "Gravel Driveway Cost",
    subtitle: "Complete driveway cost breakdown",
    description:
      "A standard 12x50-foot single-car gravel driveway costs $1,500-$6,000, or $1.25-$3.00 per square foot installed. Learn about the three-layer system and cost components.",
    icon: "road",
    sortOrder: 2,
    content: {
      totalRange: "$1,500-$6,000",
      perSqFtRange: "$1.25-$3.00/sq ft installed",
      layers: [
        {
          name: "Base Layer (4\")",
          material: "#3 or #4 stone",
          cost: "$500-$800",
          purpose: "Structural foundation and drainage",
        },
        {
          name: "Middle Layer (4\")",
          material: "#57 gravel",
          cost: "$400-$700",
          purpose: "Transition layer and stability",
        },
        {
          name: "Top Layer (2-3\")",
          material: "#8 gravel or crushed limestone",
          cost: "$300-$600",
          purpose: "Driving surface and appearance",
        },
      ],
      costComponents: [
        { component: "Materials", percentage: "40-60% of total" },
        { component: "Labor", range: "$0.50-$1.50/sq ft" },
        { component: "Drainage & Grading", range: "$200-$800" },
        { component: "Edging", range: "$2-$5/linear ft" },
        { component: "Geotextile Fabric", range: "$0.30-$0.50/sq ft" },
      ],
      alternatives: [
        {
          name: "Crusher Run Single-Layer",
          cost: "$400-$700",
          note: "Budget option — one material does it all",
        },
        {
          name: "Gravel Driveway",
          cost: "$1-$3/sq ft",
          note: "10-15 year lifespan with maintenance",
        },
        {
          name: "Concrete Driveway",
          cost: "$5-$10/sq ft",
          note: "25-30 year lifespan",
        },
      ],
    },
  },
  {
    slug: "cost-per-yard",
    title: "Gravel Cost Per Yard",
    subtitle: "Cubic yard pricing for all materials",
    description:
      "Gravel costs $15-$75 per cubic yard depending on the type. One cubic yard covers about 100 square feet at 3 inches deep and weighs 1.2-1.7 tons.",
    icon: "cube",
    sortOrder: 3,
    content: {
      generalRange: "$15-$75 per cubic yard",
      coverageNote:
        "One cubic yard covers about 100 sq ft at 3 inches deep and weighs 1.2-1.7 tons",
      pricingTable: [
        { material: "#411 Gravel", low: 25, high: 55 },
        { material: "#57 Gravel", low: 25, high: 45 },
        { material: "#8 Gravel", low: 28, high: 50 },
        { material: "#89 Stone", low: 28, high: 50 },
        { material: "Bank Run Gravel", low: 20, high: 40 },
        { material: "Crushed Limestone", low: 25, high: 50 },
        { material: "Crushed Stone", low: 25, high: 55 },
        { material: "Crusher Run", low: 25, high: 45 },
        { material: "Decomposed Granite", low: 30, high: 50 },
        { material: "Fill Dirt", low: 8, high: 25 },
        { material: "Pea Gravel", low: 30, high: 60 },
        { material: "Recycled Asphalt", low: 20, high: 45 },
        { material: "Rip Rap", low: 45, high: 100 },
        { material: "River Rock", low: 45, high: 120 },
        { material: "Stone Dust", low: 20, high: 40 },
        { material: "Topsoil", low: 15, high: 40 },
        { material: "Washed Gravel", low: 30, high: 60 },
      ],
    },
  },
  {
    slug: "cost-per-ton",
    title: "Gravel Cost Per Ton",
    subtitle: "Per-ton pricing for all materials",
    description:
      "Gravel costs $10-$50 per ton for most common types. A ton of gravel covers approximately 80-100 square feet at 2 inches deep, or 50-60 square feet at 3 inches deep.",
    icon: "weight",
    sortOrder: 4,
    content: {
      generalRange: "$10-$50 per ton",
      coverageNote:
        "A ton of gravel covers approximately 80-100 sq ft at 2 inches deep, or 50-60 sq ft at 3 inches deep",
      pricingTable: [
        { material: "#411 Gravel", low: 20, high: 40 },
        { material: "#57 Gravel", low: 20, high: 35 },
        { material: "#8 Gravel", low: 22, high: 40 },
        { material: "#89 Stone", low: 22, high: 40 },
        { material: "Bank Run Gravel", low: 15, high: 30 },
        { material: "Crushed Limestone", low: 20, high: 45 },
        { material: "Crushed Stone", low: 20, high: 40 },
        { material: "Crusher Run", low: 20, high: 35 },
        { material: "Decomposed Granite", low: 25, high: 45 },
        { material: "Fill Dirt", low: 5, high: 15 },
        { material: "Pea Gravel", low: 25, high: 50 },
        { material: "Recycled Asphalt", low: 15, high: 30 },
        { material: "Rip Rap", low: 35, high: 80 },
        { material: "River Rock", low: 40, high: 100 },
        { material: "Stone Dust", low: 15, high: 30 },
        { material: "Topsoil", low: 12, high: 30 },
        { material: "Washed Gravel", low: 25, high: 45 },
      ],
    },
  },
];

const SERVICES_DATA = [
  {
    slug: "material-sales",
    title: "Material Sales",
    description:
      "Wide selection of sand, gravel, soil, and stone products at competitive prices. On-site state-approved scales ensure accurate measurements.",
    icon: "mountain",
    features: [
      "15+ product varieties",
      "State-approved scales",
      "Competitive pricing",
      "Volume discounts available",
    ],
    sortOrder: 0,
  },
  {
    slug: "delivery-services",
    title: "Delivery Services",
    description:
      "We deliver materials directly to your job site with our fleet of trucks, handling loads up to 20 tons per trip.",
    icon: "truck",
    features: [
      "Up to 20 tons per load",
      "Serving Southeast Ohio",
      "Timely delivery",
      "Call for delivery rates",
    ],
    sortOrder: 1,
  },
  {
    slug: "large-project-pricing",
    title: "Large Project Pricing",
    description:
      "Special pricing for large-quantity orders. Whether you're a contractor or homeowner with a big project, we offer volume discounts.",
    icon: "calculator",
    features: [
      "Volume discounts",
      "Contractor pricing",
      "Project consultation",
      "Custom orders",
    ],
    sortOrder: 2,
  },
  {
    slug: "on-site-loading",
    title: "On-Site Loading",
    description:
      "State of the art equipment for fast, efficient loading. Drive in, get loaded, and get back to your project quickly.",
    icon: "loader",
    features: [
      "Fast loading times",
      "Modern equipment",
      "Accurate weights",
      "Easy access",
    ],
    sortOrder: 3,
  },
];

async function main() {
  // Clear existing data
  await prisma.productComparison.deleteMany();
  await prisma.costGuide.deleteMany();
  await prisma.product.deleteMany();

  // Seed products
  for (const product of PRODUCTS_DATA) {
    await prisma.product.create({ data: product });
  }

  // Seed cost guides
  for (const guide of COST_GUIDES_DATA) {
    await prisma.costGuide.create({ data: guide });
  }

  // Upsert services (idempotent — keeps existing rows in sync)
  for (const service of SERVICES_DATA) {
    await prisma.service.upsert({
      where: { slug: service.slug },
      create: service,
      update: service,
    });
  }

  // Create comparisons between related products
  const allProducts = await prisma.product.findMany();
  const slugMap = new Map(allProducts.map((p) => [p.slug, p]));

  const comparisons = [
    {
      a: "crusher-run",
      b: "57-gravel",
      summary:
        "Crusher run compacts into a solid surface ideal for driveways, while #57 gravel excels at drainage. Crusher run is a single-layer solution; #57 typically needs a finer top layer.",
    },
    {
      a: "pea-gravel",
      b: "river-rock",
      summary:
        "Pea gravel is smaller (3/8\") and affordable for patios and walkways. River rock (1-5\") is larger, more decorative, and better for erosion control but costs more.",
    },
    {
      a: "crushed-stone",
      b: "pea-gravel",
      summary:
        "Crushed stone has angular edges that lock together for stability — ideal for driveways. Pea gravel is smooth and rounded — more comfortable but shifts easily.",
    },
    {
      a: "crusher-run",
      b: "411-gravel",
      summary:
        "#411 gravel offers better drainage than crusher run while still compacting well. Crusher run has more fines for maximum compaction. Both work for driveways.",
    },
    {
      a: "fill-dirt",
      b: "topsoil",
      summary:
        "Fill dirt is for structural fill and grading — it compacts firmly and won't decompose. Topsoil is for growing plants — rich in nutrients but settles over time.",
    },
    {
      a: "8-gravel",
      b: "57-gravel",
      summary:
        "#8 gravel (3/8\"-1/2\") is smaller and more comfortable for walking. #57 (3/4\"-1\") is larger and better for drainage and base layers.",
    },
    {
      a: "crushed-limestone",
      b: "crushed-stone",
      summary:
        "Crushed limestone has a bright, light color and natural weed suppression. Standard crushed stone is darker but often cheaper and more widely available.",
    },
    {
      a: "decomposed-granite",
      b: "pea-gravel",
      summary:
        "Decomposed granite compacts into a firm walking surface with a rustic look. Pea gravel is smoother but shifts more — both work for patios and pathways.",
    },
    {
      a: "recycled-asphalt",
      b: "crusher-run",
      summary:
        "Recycled asphalt compacts into a semi-sealed surface with less dust. Crusher run is more traditional and widely available. Both are budget-friendly driveway options.",
    },
    {
      a: "stone-dust",
      b: "decomposed-granite",
      summary:
        "Stone dust is the standard paver base — compacts extremely tight. Decomposed granite has a more natural, rustic appearance and works better as a standalone surface.",
    },
  ];

  for (const comp of comparisons) {
    const productA = slugMap.get(comp.a);
    const productB = slugMap.get(comp.b);
    if (productA && productB) {
      await prisma.productComparison.create({
        data: {
          productAId: productA.id,
          productBId: productB.id,
          summary: comp.summary,
        },
      });
    }
  }

  const productCount = await prisma.product.count();
  const guideCount = await prisma.costGuide.count();
  const compCount = await prisma.productComparison.count();
  const serviceCount = await prisma.service.count();
  process.stdout.write(
    `Seeded ${productCount} products, ${guideCount} cost guides, ${compCount} comparisons, ${serviceCount} services\n`
  );
}

main()
  .catch((e) => {
    process.stderr.write(String(e) + "\n");
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
