import { defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 6,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "image",
      title: "Image",
      type: "image",
      options: { hotspot: true },
      fields: [
        {
          name: "alt",
          title: "Alt Text",
          type: "string",
        },
      ],
    }),
    defineField({
      name: "price",
      title: "Price",
      type: "number",
      description: "Muskingum local pricing",
    }),
    defineField({
      name: "unit",
      title: "Unit",
      type: "string",
      initialValue: "ton",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "marketPriceLowPerTon",
      title: "Market Price Low (per ton)",
      type: "number",
      description: "Industry low-end pricing per ton",
    }),
    defineField({
      name: "marketPriceHighPerTon",
      title: "Market Price High (per ton)",
      type: "number",
      description: "Industry high-end pricing per ton",
    }),
    defineField({
      name: "marketPriceLowPerYard",
      title: "Market Price Low (per yard)",
      type: "number",
      description: "Industry low-end pricing per cubic yard",
    }),
    defineField({
      name: "marketPriceHighPerYard",
      title: "Market Price High (per yard)",
      type: "number",
      description: "Industry high-end pricing per cubic yard",
    }),
    defineField({
      name: "sizeDescription",
      title: "Size Description",
      type: "string",
      description: "Physical size description (e.g., '1-3 inches')",
    }),
    defineField({
      name: "colorDescription",
      title: "Color Description",
      type: "string",
      description: "Color description (e.g., 'gray', 'tan')",
    }),
    defineField({
      name: "densityLow",
      title: "Density Low",
      type: "number",
      initialValue: 1.4,
      description: "Low-end density (tons per cubic yard)",
    }),
    defineField({
      name: "densityHigh",
      title: "Density High",
      type: "number",
      initialValue: 1.5,
      description: "High-end density (tons per cubic yard)",
    }),
    defineField({
      name: "bestFor",
      title: "Best For",
      type: "array",
      of: [{ type: "string" }],
      description: "List of use cases this product is best suited for",
    }),
    defineField({
      name: "notFor",
      title: "Not For",
      type: "array",
      of: [{ type: "string" }],
      description: "List of use cases this product is NOT suited for",
    }),
    defineField({
      name: "commonUses",
      title: "Common Uses",
      type: "array",
      of: [{ type: "string" }],
      description: "Common applications and uses",
    }),
    defineField({
      name: "pros",
      title: "Pros",
      type: "array",
      of: [{ type: "string" }],
      description: "Advantages of this product",
    }),
    defineField({
      name: "cons",
      title: "Cons",
      type: "array",
      of: [{ type: "string" }],
      description: "Disadvantages or limitations",
    }),
    defineField({
      name: "altNames",
      title: "Alternative Names",
      type: "array",
      of: [{ type: "string" }],
      description: "Other common names for this product",
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
      description: "SEO meta title",
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
      description: "SEO meta description",
    }),
    defineField({
      name: "sortOrder",
      title: "Sort Order",
      type: "number",
      initialValue: 0,
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "active",
      title: "Active",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "stockStatus",
      title: "Stock Status",
      type: "string",
      options: {
        list: [
          { title: "In Stock", value: "IN_STOCK" },
          { title: "Low Stock", value: "LOW_STOCK" },
          { title: "Out of Stock", value: "OUT_OF_STOCK" },
          { title: "Seasonal", value: "SEASONAL" },
        ],
      },
      initialValue: "IN_STOCK",
    }),
    defineField({
      name: "seasonalMessage",
      title: "Seasonal Message",
      type: "string",
      description: "Message to display when product is seasonal or unavailable",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "category",
      media: "image"
    },
  },
});
